import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "./components/Header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Header />

      <main>
        <div className="px-20 py-56 text-white bg-cover bg-center bg-slate-700 bg-blend-lighten min-h-[900px] bg-[url('/dorfschule2.jpg')] absolute w-full top-0 -z-10">
          <p>Das ist Test Text</p>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
