import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "./components/header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <main>
        <div className="px-20 py-56 text-white bg-cover bg-center bg-slate-700 bg-blend-lighten min-h-[900px] bg-[url('/dorfschule2.jpg')] absolute w-full top-0 -z-10">
          <h1>test</h1>
          <p>Das ist Test Text</p>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
