import React from "react";
import Head from "next/head";

import Header from "./components/Header";

function Verein() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Header darkNav="true" />

      <main>
        <div className="p-20 text-slate-700">
          <p>Das Verein</p>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}

export default Verein;
